---

- name: install i3 windowmanager and components
  pacman:
    name:
      - xorg
      - xorg-xinit
      - i3-gaps
      - i3lock
      - i3status-rust
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install components
  pacman:
    name:
    - dmenu
    - feh
    - dunst
    - rofi
    - compton
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install i3lock fancy and glitchlock from aur
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  with_items:
    - i3lock-fancy-dualmonitors-git
    - glitchlock
    - rofi-power-menu

- name: create i3wm configuration directory and util subdirectory
  file:
    name: /home/{{ user.name }}/.i3/util
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: copy X11 config
  copy:
    src: "{{ item }}"
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
  with_items:
    - 00-keyboard.conf
    - 50-mouse-acceleration.conf
    - 50-mouse-deceleration.conf