---
- name: Install oh-my-zsh-git and optional dependencies from AUR
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - oh-my-zsh-git
    - oh-my-zsh-powerline-theme-git
  register: omzinstall
  until: omzinstall is success
  retries: 10
  delay: 2

- name: Install ZSH with completion and syntax
  pacman:
    name:
     - zsh
     - zsh-completions
     - zsh-syntax-highlighting
     - zsh-theme-powerlevel10k
    state: present
  register: zshinstall
  until: zshinstall is success
  retries: 10
  delay: 2
  notify: change shell

- name: Ensure the cache folder with oh-my-zsh subfolder is present
  file:
    path: /home/{{ user.name }}/.cache/oh-my-zsh
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
    mode: 0755
  when: omzinstall is changed

- name: Ensure the last working dir file for oh-my-zsh is present
  file:
    path: /home/{{ user.name }}/.cache/oh-my-zsh/last-working-dir
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: touch
  when: omzinstall is changed

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/usr/share/oh-my-zsh/custom/plugins/zsh-autosuggestions"
    accept_hostkey: true
    update: true
    force: true