---

- name: Install w3m
  pacman: name=w3m state=present

- name: Install firefox
  pacman: name=firefox state=present
  tags:
    - firefox

- name: Install tor-browser-en
  aur: 
    name: tor-browser-en
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - tor-browser
    - aur
