---
- name: Install signal-desktop and discord
  pacman:
    name: 
      - signal-desktop
      - discord
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Jail signal-desktop
  file: src=/usr/bin/firejail
        dest=/usr/bin/signal-desktop
        state=link
  tags:
    - firejail

- name: Jail discord
  file: src=/usr/bin/firejail
        dest=/usr/bin/discord
        state=link
  tags:
    - firejail
