---
- name: Install signal-desktop
  pacman:
    name: signal-desktop
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Jail signal-desktop
  file: src=/usr/bin/firejail
        dest=/usr/bin/signal-desktop
        state=link
  tags:
    - firejail
